### PR TITLE
Add coverity badge

### PR DESCRIPTION
**Pull request by lord2800**
Once our initial scan finishes, we can merge this. After I fix the conflicts.

### CODE REVIEW

**Comment by lord2800** [comment]
Conflicts fixed.

**Comment by gabelimon** [comment]
I assume this is the proper SVG :+1:

**Comment by lord2800** [comment]
Turns out I need to do some configuring to Travis to make it submit scans before this will work.

**Comment by lord2800** [comment]
Well, it doesn't break things. I'll make a tag to test this after I merge.

**Pull request merged**
